// Package proto defines the wire protocol shared by dingzi-agent and
// dingzi-server.
//
// Transport is a single WebSocket connection carrying JSON text frames. Every
// frame is an [Envelope]. This is deliberately boring: it survives CDNs,
// reverse proxies and corporate middleboxes that mangle gRPC, and it can be
// read with a browser devtools window when something goes wrong.
package proto

import (
	"encoding/json"
	"fmt"
)

// Version is the protocol version. The server accepts any agent whose major
// version matches; unknown message types are ignored rather than fatal so that
// a newer server can talk to an older agent.
const Version = 1

// Path is the WebSocket endpoint agents connect to.
const Path = "/api/v1/agent/ws"

// Message types sent by the agent.
const (
	// TypeHello is the first frame on every connection: identity plus static
	// host facts. The server replies with [TypeWelcome].
	TypeHello = "hello"
	// TypeState is a periodic metrics sample.
	TypeState = "state"
	// TypeHostUpdate reports changed static host facts (kernel upgrade, disk
	// added). Sent rarely, not on every sample.
	TypeHostUpdate = "host_update"
	// TypeTaskResult carries the outcome of a dispatched [Task].
	TypeTaskResult = "task_result"
	// TypePong answers [TypePing].
	TypePong = "pong"
)

// Message types sent by the server.
const (
	// TypeWelcome accepts a [Hello] and hands the agent its runtime config.
	TypeWelcome = "welcome"
	// TypeTask dispatches work (a reachability check, a shell command).
	TypeTask = "task"
	// TypePing is an application-level liveness probe. It rides above the
	// WebSocket control ping because some proxies swallow control frames.
	TypePing = "ping"
	// TypeError reports a problem with the previous frame. Fatal errors are
	// followed by the server closing the connection.
	TypeError = "error"
)

// Envelope wraps every frame. Data holds the type-specific payload.
type Envelope struct {
	V    int             `json:"v"`
	Type string          `json:"type"`
	// ID correlates a response with its request. Empty for unsolicited frames.
	ID   string          `json:"id,omitempty"`
	Data json.RawMessage `json:"data,omitempty"`
}

// Encode marshals payload into an envelope of the given type.
func Encode(typ, id string, payload any) ([]byte, error) {
	env := Envelope{V: Version, Type: typ, ID: id}
	if payload != nil {
		raw, err := json.Marshal(payload)
		if err != nil {
			return nil, fmt.Errorf("proto: marshal %s payload: %w", typ, err)
		}
		env.Data = raw
	}
	return json.Marshal(env)
}

// Decode unmarshals an envelope's payload into out.
func Decode(env *Envelope, out any) error {
	if len(env.Data) == 0 {
		return fmt.Errorf("proto: %s frame has no payload", env.Type)
	}
	if err := json.Unmarshal(env.Data, out); err != nil {
		return fmt.Errorf("proto: unmarshal %s payload: %w", env.Type, err)
	}
	return nil
}

// Hello identifies an agent to the server.
type Hello struct {
	// UUID is generated by the agent on first run and persisted. It is the
	// stable identity of a machine across reinstalls of the agent binary.
	UUID string `json:"uuid"`
	// Version is the agent build version, for the "agent needs updating" hint.
	Version string `json:"version"`
	// Name is an optional operator-supplied display name. The server only
	// applies it when the machine is first registered, so renaming a server in
	// the UI is not clobbered by the next reconnect.
	Name string `json:"name,omitempty"`
	Host Host   `json:"host"`
}

// Welcome is the server's answer to a [Hello].
type Welcome struct {
	// ServerID is the panel's numeric id for this machine.
	ServerID int64 `json:"server_id"`
	// Name is the display name the panel knows this machine by.
	Name string `json:"name"`
	// Interval is the seconds between [State] reports the server wants.
	Interval float64 `json:"interval"`
	// ServerTimeMS lets the agent report clock skew instead of silently
	// producing samples the panel has to guess timestamps for.
	ServerTimeMS int64 `json:"server_time_ms"`
}

// ErrorPayload is the body of a [TypeError] frame.
type ErrorPayload struct {
	Message string `json:"message"`
	// Fatal means the server is about to close the connection and the agent
	// should not retry with the same inputs (bad secret, protocol mismatch).
	Fatal bool `json:"fatal"`
}
